project:
  type: website
  output-dir: docs

website:
  title: "Climatic Niche Characterization"
  navbar:
    left:
      - href: about.qmd
        text: Home
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "About"
        href: about.qmd
        contents: about.qmd
      - section: "Spartina"
        href: spartina.qmd
        contents: spartina.qmd
      - section: "Mikania"
        href: mikania.qmd
        contents: mikania.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual